name: Mercari Watch
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ensure state file
        run: |
          mkdir -p data
          if [ ! -f data/seen_ids.json ]; then echo "[]" > data/seen_ids.json; fi
      - name: Run watcher
        env:
          SEARCH_URL: ${{ secrets.SEARCH_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COLOR_KEYWORDS: ${{ secrets.COLOR_KEYWORDS }}
          MIN_PRICE: ${{ secrets.MIN_PRICE }}
          MAX_PRICE: ${{ secrets.MAX_PRICE }}
        run: python watcher.py
      - name: Commit state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/seen_ids.json
          git commit -m "chore: update seen_ids $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
